
import "../blocks/aluminum_wire.js"
import "../blocks/fluid_tank.js"
import "../blocks/fluid_pipe.js"
import "../blocks/stairs.js"
import "../blocks/rocket_launch_pad.js"
import "../blocks/buggy_fueling_pad.js"
import "../blocks/arc_lamp.js"
import "../blocks/cheese_block.js"
import "../blocks/hydraulic_platform.js"
import "../blocks/nasa_workbench.js"
import "../blocks/cavernous_vines.js"
import "../blocks/treasure_chest.js"
import "../blocks/dishbase.js"
import "../blocks/fallen_meteor.js"
